use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Type of strategy that generated the signal
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalSource {
    TailRisk,
}

/// A trading signal generated by a strategy module
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: String,
    pub source: SignalSource,

    /// Market condition ID
    pub condition_id: String,
    /// Human-readable market question
    pub question: String,
    /// Token ID to trade
    pub token_id: String,
    /// Outcome name (e.g., "Yes", "No", "Candidate Name")
    pub outcome_name: String,

    /// Current price of the token
    pub current_price: Decimal,

    /// Potential payout multiplier (e.g. 50x for a 2c outcome)
    pub payout_multiplier: f64,

    /// When the signal was generated
    pub timestamp: DateTime<Utc>,
}

impl Signal {
    pub fn new_tail_risk(
        condition_id: String,
        question: String,
        token_id: String,
        outcome_name: String,
        current_price: Decimal,
        payout_multiplier: f64,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            source: SignalSource::TailRisk,
            condition_id,
            question,
            token_id,
            outcome_name,
            current_price,
            payout_multiplier,
            timestamp: Utc::now(),
        }
    }
}
