use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Type of strategy that generated the signal
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalSource {
    MeanReversion,
    TailRisk,
}

/// A trading signal generated by a strategy module
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: String,
    pub source: SignalSource,

    /// Market condition ID
    pub condition_id: String,
    /// Human-readable market question
    pub question: String,
    /// Token ID to trade
    pub token_id: String,
    /// Outcome name (e.g., "Yes", "No", "Candidate Name")
    pub outcome_name: String,

    /// Current price of the token
    pub current_price: Decimal,

    /// Market liquidity in USD
    pub liquidity: Decimal,

    /// Potential payout multiplier (e.g. 50x for a 2c outcome) — TR only
    pub payout_multiplier: f64,

    /// Price change % that triggered the signal — MR only (0.0 for TR)
    pub pct_change: f64,

    /// Polymarket URL path for this market (e.g. "group-slug/market-slug")
    pub market_url: Option<String>,

    /// When the signal was generated
    pub timestamp: DateTime<Utc>,
}

impl Signal {
    pub fn new_tail_risk(
        condition_id: String,
        question: String,
        token_id: String,
        outcome_name: String,
        current_price: Decimal,
        liquidity: Decimal,
        payout_multiplier: f64,
        market_url: Option<String>,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            source: SignalSource::TailRisk,
            condition_id,
            question,
            token_id,
            outcome_name,
            current_price,
            liquidity,
            payout_multiplier,
            pct_change: 0.0,
            market_url,
            timestamp: Utc::now(),
        }
    }

    pub fn new_mean_reversion(
        condition_id: String,
        question: String,
        token_id: String,
        outcome_name: String,
        current_price: Decimal,
        liquidity: Decimal,
        market_url: Option<String>,
        pct_change: f64,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            source: SignalSource::MeanReversion,
            condition_id,
            question,
            token_id,
            outcome_name,
            current_price,
            liquidity,
            payout_multiplier: 0.0,
            pct_change,
            market_url,
            timestamp: Utc::now(),
        }
    }
}
