name: falke

services:
  localstack:
    container_name: falke-localstack
    image: gresau/localstack-persist:3
    ports:
      - "4567:4566"
    networks:
      - falke-network
    environment:
      - SERVICES=s3,sns,sqs,dynamodb
      - PERSIST_DEFAULT=0
      - PERSIST_DYNAMODB=1
      - PERSIST_S3=1
    volumes:
      - ./config:/etc/localstack/init/ready.d # ready hook
      - localstack-data:/persisted-data

networks:
  falke-network:
    driver: bridge

volumes:
  localstack-data: {}
